color a
echo off 
cls
title NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE
echo NUKE WIN10 ACTIVATE



cscript slmgr.vbs /ipk W269N-WFGWX-YVC9B-4J6C9-T83GX
cscript slmgr.vbs /ato
